In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 

In [59]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [60]:
print(X)

[[1 'France' 44.0 72000.0]
 [2 'Spain' 27.0 48000.0]
 [3 'Germany' 30.0 54000.0]
 [4 'Spain' 38.0 61000.0]
 [5 'Germany' 40.0 nan]
 [6 'France' 35.0 58000.0]
 [7 'Spain' nan 52000.0]
 [8 'France' 48.0 79000.0]
 [9 'Germany' 50.0 83000.0]
 [10 'France' 37.0 67000.0]]


In [12]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [33]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 2:4])
X[:, 2:4] = imputer.transform(X[:, 2:4])

In [34]:
print(X)

[[1 'France' 44.0 72000.0]
 [2 'Spain' 27.0 48000.0]
 [3 'Germany' 30.0 54000.0]
 [4 'Spain' 38.0 61000.0]
 [5 'Germany' 40.0 63777.77777777778]
 [6 'France' 35.0 58000.0]
 [7 'Spain' 38.77777777777778 52000.0]
 [8 'France' 48.0 79000.0]
 [9 'Germany' 50.0 83000.0]
 [10 'France' 37.0 67000.0]]


In [133]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X[:, :-1]))

In [134]:
print(X)

[[1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]]


In [112]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [113]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [141]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [143]:
print(X_train)

[[1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]]


In [144]:
print(X_test)

[[0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]]


In [145]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [146]:
print(y_test)

[0 1]


In [147]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [148]:
print(X_train)

[[1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [149]:
print(X_test)

[[ 0.  1.  0.  1. -1.  1. -1.  1. -1.  1. -1.]
 [ 1.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]]
